# This is a basic workflow to help you get started with Actions

name: personal-finance-CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4

      # Setup nodeJS
      - name: Setup nodeJS
        uses: actions/setup-node@v4.3.0

      # Install dependencies
      - name: Install deps
        run: npm i

      # Build app for production
      - name: Build app boundle
        run: npm run build:prod

      # Deploy to Github Pages
      - name: Deploy to Pages
        uses: crazy-max/ghaction-github-pages@v4.2.0
        with:
          build_dir: dist/
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        
